server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage: Spring Cloud GateWay Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - CustomFilter
            - RewritePath=/member/(?<segment>.*), /$\{segment}
        - id: bankBook-service
          uri: lb://BANKBOOK-SERVICE
          predicates:
            - Path=/bankbook/**
          filters:
            - CustomFilter
            - RewritePath=/bankbook/(?<segment>.*), /$\{segment}
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card/**
          filters:
            - CustomFilter
            - RewritePath=/card/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /$\{segment}
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /$\{segment}
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges
