server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage: Spring Cloud GateWay Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - CustomFilter
        - id: bankBook-service
          uri: lb://BANKBOOK-SERVICE
          predicates:
            - Path=/bankbook/**
          filters:
            - CustomFilter
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card/**
          filters:
            - CustomFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - CustomFilter
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi there.
                preLogger: false
                postLogger: false